# Generated by Django 3.2.16 on 2022-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20221116_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watchlisist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
